// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projeto.proto

package proto.example;

public interface CatalogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Catalog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Catalog.Owner people = 1;</code>
   */
  java.util.List<proto.example.Catalog.Owner> 
      getPeopleList();
  /**
   * <code>repeated .tutorial.Catalog.Owner people = 1;</code>
   */
  proto.example.Catalog.Owner getPeople(int index);
  /**
   * <code>repeated .tutorial.Catalog.Owner people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .tutorial.Catalog.Owner people = 1;</code>
   */
  java.util.List<? extends proto.example.Catalog.OwnerOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .tutorial.Catalog.Owner people = 1;</code>
   */
  proto.example.Catalog.OwnerOrBuilder getPeopleOrBuilder(
      int index);
}
