// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

public interface CatalogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Owner allOwners = 1;</code>
   */
  java.util.List<Owner> 
      getAllOwnersList();
  /**
   * <code>repeated .Owner allOwners = 1;</code>
   */
  Owner getAllOwners(int index);
  /**
   * <code>repeated .Owner allOwners = 1;</code>
   */
  int getAllOwnersCount();
  /**
   * <code>repeated .Owner allOwners = 1;</code>
   */
  java.util.List<? extends OwnerOrBuilder> 
      getAllOwnersOrBuilderList();
  /**
   * <code>repeated .Owner allOwners = 1;</code>
   */
  OwnerOrBuilder getAllOwnersOrBuilder(
      int index);

  /**
   * <code>repeated .Pet allPets = 2;</code>
   */
  java.util.List<Pet> 
      getAllPetsList();
  /**
   * <code>repeated .Pet allPets = 2;</code>
   */
  Pet getAllPets(int index);
  /**
   * <code>repeated .Pet allPets = 2;</code>
   */
  int getAllPetsCount();
  /**
   * <code>repeated .Pet allPets = 2;</code>
   */
  java.util.List<? extends PetOrBuilder> 
      getAllPetsOrBuilderList();
  /**
   * <code>repeated .Pet allPets = 2;</code>
   */
  PetOrBuilder getAllPetsOrBuilder(
      int index);
}
