// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

import javax.xml.bind.annotation.*;

/**
 * Protobuf type {@code Owner}
 */
@XmlRootElement
public final class Owner extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Owner)
    OwnerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Owner.newBuilder() to construct.
  private Owner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Owner() {
    name_ = "";
    birth_ = "";
    address_ = "";
    pets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Owner();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Owner(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            ownerId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            birth_ = s;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            telephone_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000010;
            address_ = s;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              pets_ = new java.util.ArrayList<Pet>();
              mutable_bitField0_ |= 0x00000020;
            }
            pets_.add(
                input.readMessage(Pet.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        pets_ = java.util.Collections.unmodifiableList(pets_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CatalogOuterClass.internal_static_Owner_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CatalogOuterClass.internal_static_Owner_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Owner.class, Owner.Builder.class);
  }

  private int bitField0_;
  public static final int OWNER_ID_FIELD_NUMBER = 1;
  private int ownerId_;
  /**
   * <code>optional int32 owner_id = 1;</code>
   * @return Whether the ownerId field is set.
   */
  @java.lang.Override
  public boolean hasOwnerId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 owner_id = 1;</code>
   * @return The ownerId.
   */
  @java.lang.Override
  public int getOwnerId() {
    return ownerId_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIRTH_FIELD_NUMBER = 3;
  private volatile java.lang.Object birth_;
  /**
   * <code>optional string birth = 3;</code>
   * @return Whether the birth field is set.
   */
  @java.lang.Override
  public boolean hasBirth() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string birth = 3;</code>
   * @return The birth.
   */
  @java.lang.Override
  public java.lang.String getBirth() {
    java.lang.Object ref = birth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      birth_ = s;
      return s;
    }
  }
  /**
   * <code>optional string birth = 3;</code>
   * @return The bytes for birth.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBirthBytes() {
    java.lang.Object ref = birth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      birth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TELEPHONE_FIELD_NUMBER = 4;
  private long telephone_;
  /**
   * <code>optional int64 telephone = 4;</code>
   * @return Whether the telephone field is set.
   */
  @java.lang.Override
  public boolean hasTelephone() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int64 telephone = 4;</code>
   * @return The telephone.
   */
  @java.lang.Override
  public long getTelephone() {
    return telephone_;
  }

  public static final int ADDRESS_FIELD_NUMBER = 5;
  private volatile java.lang.Object address_;
  /**
   * <code>optional string address = 5;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PETS_FIELD_NUMBER = 6;
  private java.util.List<Pet> pets_;
  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  @java.lang.Override
  public java.util.List<Pet> getPetsList() {
    return pets_;
  }
  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends PetOrBuilder> 
      getPetsOrBuilderList() {
    return pets_;
  }
  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  @java.lang.Override
  public int getPetsCount() {
    return pets_.size();
  }
  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  @java.lang.Override
  public Pet getPets(int index) {
    return pets_.get(index);
  }
  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  @java.lang.Override
  public PetOrBuilder getPetsOrBuilder(
      int index) {
    return pets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, ownerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, birth_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt64(4, telephone_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
    }
    for (int i = 0; i < pets_.size(); i++) {
      output.writeMessage(6, pets_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ownerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, birth_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, telephone_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
    }
    for (int i = 0; i < pets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, pets_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Owner)) {
      return super.equals(obj);
    }
    Owner other = (Owner) obj;

    if (hasOwnerId() != other.hasOwnerId()) return false;
    if (hasOwnerId()) {
      if (getOwnerId()
          != other.getOwnerId()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasBirth() != other.hasBirth()) return false;
    if (hasBirth()) {
      if (!getBirth()
          .equals(other.getBirth())) return false;
    }
    if (hasTelephone() != other.hasTelephone()) return false;
    if (hasTelephone()) {
      if (getTelephone()
          != other.getTelephone()) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getPetsList()
        .equals(other.getPetsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOwnerId()) {
      hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerId();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasBirth()) {
      hash = (37 * hash) + BIRTH_FIELD_NUMBER;
      hash = (53 * hash) + getBirth().hashCode();
    }
    if (hasTelephone()) {
      hash = (37 * hash) + TELEPHONE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTelephone());
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (getPetsCount() > 0) {
      hash = (37 * hash) + PETS_FIELD_NUMBER;
      hash = (53 * hash) + getPetsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Owner parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Owner parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Owner parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Owner parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Owner parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Owner parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Owner parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Owner parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Owner parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Owner parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Owner parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Owner parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Owner prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Owner}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Owner)
      OwnerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CatalogOuterClass.internal_static_Owner_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CatalogOuterClass.internal_static_Owner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Owner.class, Owner.Builder.class);
    }

    // Construct using Owner.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPetsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ownerId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      birth_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      telephone_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      address_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      if (petsBuilder_ == null) {
        pets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        petsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CatalogOuterClass.internal_static_Owner_descriptor;
    }

    @java.lang.Override
    public Owner getDefaultInstanceForType() {
      return Owner.getDefaultInstance();
    }

    @java.lang.Override
    public Owner build() {
      Owner result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Owner buildPartial() {
      Owner result = new Owner(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ownerId_ = ownerId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.birth_ = birth_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.telephone_ = telephone_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.address_ = address_;
      if (petsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          pets_ = java.util.Collections.unmodifiableList(pets_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.pets_ = pets_;
      } else {
        result.pets_ = petsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Owner) {
        return mergeFrom((Owner)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Owner other) {
      if (other == Owner.getDefaultInstance()) return this;
      if (other.hasOwnerId()) {
        setOwnerId(other.getOwnerId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasBirth()) {
        bitField0_ |= 0x00000004;
        birth_ = other.birth_;
        onChanged();
      }
      if (other.hasTelephone()) {
        setTelephone(other.getTelephone());
      }
      if (other.hasAddress()) {
        bitField0_ |= 0x00000010;
        address_ = other.address_;
        onChanged();
      }
      if (petsBuilder_ == null) {
        if (!other.pets_.isEmpty()) {
          if (pets_.isEmpty()) {
            pets_ = other.pets_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensurePetsIsMutable();
            pets_.addAll(other.pets_);
          }
          onChanged();
        }
      } else {
        if (!other.pets_.isEmpty()) {
          if (petsBuilder_.isEmpty()) {
            petsBuilder_.dispose();
            petsBuilder_ = null;
            pets_ = other.pets_;
            bitField0_ = (bitField0_ & ~0x00000020);
            petsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPetsFieldBuilder() : null;
          } else {
            petsBuilder_.addAllMessages(other.pets_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Owner parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Owner) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int ownerId_ ;
    /**
     * <code>optional int32 owner_id = 1;</code>
     * @return Whether the ownerId field is set.
     */
    @java.lang.Override
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 owner_id = 1;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public int getOwnerId() {
      return ownerId_;
    }
    /**
     * <code>optional int32 owner_id = 1;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(int value) {
      bitField0_ |= 0x00000001;
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 owner_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ownerId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object birth_ = "";
    /**
     * <code>optional string birth = 3;</code>
     * @return Whether the birth field is set.
     */
    public boolean hasBirth() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string birth = 3;</code>
     * @return The birth.
     */
    public java.lang.String getBirth() {
      java.lang.Object ref = birth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string birth = 3;</code>
     * @return The bytes for birth.
     */
    public com.google.protobuf.ByteString
        getBirthBytes() {
      java.lang.Object ref = birth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string birth = 3;</code>
     * @param value The birth to set.
     * @return This builder for chaining.
     */
    public Builder setBirth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      birth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string birth = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBirth() {
      bitField0_ = (bitField0_ & ~0x00000004);
      birth_ = getDefaultInstance().getBirth();
      onChanged();
      return this;
    }
    /**
     * <code>optional string birth = 3;</code>
     * @param value The bytes for birth to set.
     * @return This builder for chaining.
     */
    public Builder setBirthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      birth_ = value;
      onChanged();
      return this;
    }

    private long telephone_ ;
    /**
     * <code>optional int64 telephone = 4;</code>
     * @return Whether the telephone field is set.
     */
    @java.lang.Override
    public boolean hasTelephone() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int64 telephone = 4;</code>
     * @return The telephone.
     */
    @java.lang.Override
    public long getTelephone() {
      return telephone_;
    }
    /**
     * <code>optional int64 telephone = 4;</code>
     * @param value The telephone to set.
     * @return This builder for chaining.
     */
    public Builder setTelephone(long value) {
      bitField0_ |= 0x00000008;
      telephone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 telephone = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTelephone() {
      bitField0_ = (bitField0_ & ~0x00000008);
      telephone_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>optional string address = 5;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000010);
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }

    private java.util.List<Pet> pets_ =
      java.util.Collections.emptyList();
    private void ensurePetsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        pets_ = new java.util.ArrayList<Pet>(pets_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Pet, Pet.Builder, PetOrBuilder> petsBuilder_;

    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public java.util.List<Pet> getPetsList() {
      if (petsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pets_);
      } else {
        return petsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public int getPetsCount() {
      if (petsBuilder_ == null) {
        return pets_.size();
      } else {
        return petsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Pet getPets(int index) {
      if (petsBuilder_ == null) {
        return pets_.get(index);
      } else {
        return petsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Builder setPets(
        int index, Pet value) {
      if (petsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetsIsMutable();
        pets_.set(index, value);
        onChanged();
      } else {
        petsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Builder setPets(
        int index, Pet.Builder builderForValue) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.set(index, builderForValue.build());
        onChanged();
      } else {
        petsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Builder addPets(Pet value) {
      if (petsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetsIsMutable();
        pets_.add(value);
        onChanged();
      } else {
        petsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Builder addPets(
        int index, Pet value) {
      if (petsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetsIsMutable();
        pets_.add(index, value);
        onChanged();
      } else {
        petsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Builder addPets(
        Pet.Builder builderForValue) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.add(builderForValue.build());
        onChanged();
      } else {
        petsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Builder addPets(
        int index, Pet.Builder builderForValue) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.add(index, builderForValue.build());
        onChanged();
      } else {
        petsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Builder addAllPets(
        java.lang.Iterable<? extends Pet> values) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pets_);
        onChanged();
      } else {
        petsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Builder clearPets() {
      if (petsBuilder_ == null) {
        pets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        petsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Builder removePets(int index) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.remove(index);
        onChanged();
      } else {
        petsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Pet.Builder getPetsBuilder(
        int index) {
      return getPetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public PetOrBuilder getPetsOrBuilder(
        int index) {
      if (petsBuilder_ == null) {
        return pets_.get(index);  } else {
        return petsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public java.util.List<? extends PetOrBuilder> 
         getPetsOrBuilderList() {
      if (petsBuilder_ != null) {
        return petsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pets_);
      }
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Pet.Builder addPetsBuilder() {
      return getPetsFieldBuilder().addBuilder(
          Pet.getDefaultInstance());
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public Pet.Builder addPetsBuilder(
        int index) {
      return getPetsFieldBuilder().addBuilder(
          index, Pet.getDefaultInstance());
    }
    /**
     * <code>repeated .Pet pets = 6;</code>
     */
    public java.util.List<Pet.Builder> 
         getPetsBuilderList() {
      return getPetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Pet, Pet.Builder, PetOrBuilder> 
        getPetsFieldBuilder() {
      if (petsBuilder_ == null) {
        petsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Pet, Pet.Builder, PetOrBuilder>(
                pets_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        pets_ = null;
      }
      return petsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Owner)
  }

  // @@protoc_insertion_point(class_scope:Owner)
  private static final Owner DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Owner();
  }

  public static Owner getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Owner>
      PARSER = new com.google.protobuf.AbstractParser<Owner>() {
    @java.lang.Override
    public Owner parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Owner(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Owner> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Owner> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Owner getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

