// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

public interface OwnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Owner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 owner_id = 1;</code>
   * @return Whether the ownerId field is set.
   */
  boolean hasOwnerId();
  /**
   * <code>optional int32 owner_id = 1;</code>
   * @return The ownerId.
   */
  int getOwnerId();

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string birth = 3;</code>
   * @return Whether the birth field is set.
   */
  boolean hasBirth();
  /**
   * <code>optional string birth = 3;</code>
   * @return The birth.
   */
  java.lang.String getBirth();
  /**
   * <code>optional string birth = 3;</code>
   * @return The bytes for birth.
   */
  com.google.protobuf.ByteString
      getBirthBytes();

  /**
   * <code>optional int64 telephone = 4;</code>
   * @return Whether the telephone field is set.
   */
  boolean hasTelephone();
  /**
   * <code>optional int64 telephone = 4;</code>
   * @return The telephone.
   */
  long getTelephone();

  /**
   * <code>optional string address = 5;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 5;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  java.util.List<Pet> 
      getPetsList();
  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  Pet getPets(int index);
  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  int getPetsCount();
  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  java.util.List<? extends PetOrBuilder> 
      getPetsOrBuilderList();
  /**
   * <code>repeated .Pet pets = 6;</code>
   */
  PetOrBuilder getPetsOrBuilder(
      int index);
}
