// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

/**
 * Protobuf type {@code Pet}
 */
public final class Pet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Pet)
    PetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Pet.newBuilder() to construct.
  private Pet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Pet() {
    name_ = "";
    species_ = "";
    gender_ = "";
    birth_ = "";
    formDesc_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Pet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Pet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            petId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            species_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000008;
            gender_ = s;
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            weight_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000020;
            birth_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000040;
            formDesc_ = s;
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            ownerId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CatalogOuterClass.internal_static_Pet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CatalogOuterClass.internal_static_Pet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Pet.class, Pet.Builder.class);
  }

  private int bitField0_;
  public static final int PET_ID_FIELD_NUMBER = 1;
  private int petId_;
  /**
   * <code>optional int32 pet_id = 1;</code>
   * @return Whether the petId field is set.
   */
  @java.lang.Override
  public boolean hasPetId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 pet_id = 1;</code>
   * @return The petId.
   */
  @java.lang.Override
  public int getPetId() {
    return petId_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPECIES_FIELD_NUMBER = 3;
  private volatile java.lang.Object species_;
  /**
   * <code>optional string species = 3;</code>
   * @return Whether the species field is set.
   */
  @java.lang.Override
  public boolean hasSpecies() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string species = 3;</code>
   * @return The species.
   */
  @java.lang.Override
  public java.lang.String getSpecies() {
    java.lang.Object ref = species_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      species_ = s;
      return s;
    }
  }
  /**
   * <code>optional string species = 3;</code>
   * @return The bytes for species.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpeciesBytes() {
    java.lang.Object ref = species_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      species_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 4;
  private volatile java.lang.Object gender_;
  /**
   * <code>optional string gender = 4;</code>
   * @return Whether the gender field is set.
   */
  @java.lang.Override
  public boolean hasGender() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string gender = 4;</code>
   * @return The gender.
   */
  @java.lang.Override
  public java.lang.String getGender() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gender_ = s;
      return s;
    }
  }
  /**
   * <code>optional string gender = 4;</code>
   * @return The bytes for gender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenderBytes() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEIGHT_FIELD_NUMBER = 5;
  private int weight_;
  /**
   * <code>optional int32 weight = 5;</code>
   * @return Whether the weight field is set.
   */
  @java.lang.Override
  public boolean hasWeight() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 weight = 5;</code>
   * @return The weight.
   */
  @java.lang.Override
  public int getWeight() {
    return weight_;
  }

  public static final int BIRTH_FIELD_NUMBER = 6;
  private volatile java.lang.Object birth_;
  /**
   * <code>optional string birth = 6;</code>
   * @return Whether the birth field is set.
   */
  @java.lang.Override
  public boolean hasBirth() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string birth = 6;</code>
   * @return The birth.
   */
  @java.lang.Override
  public java.lang.String getBirth() {
    java.lang.Object ref = birth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      birth_ = s;
      return s;
    }
  }
  /**
   * <code>optional string birth = 6;</code>
   * @return The bytes for birth.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBirthBytes() {
    java.lang.Object ref = birth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      birth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORM_DESC_FIELD_NUMBER = 7;
  private volatile java.lang.Object formDesc_;
  /**
   * <code>optional string form_desc = 7;</code>
   * @return Whether the formDesc field is set.
   */
  @java.lang.Override
  public boolean hasFormDesc() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string form_desc = 7;</code>
   * @return The formDesc.
   */
  @java.lang.Override
  public java.lang.String getFormDesc() {
    java.lang.Object ref = formDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      formDesc_ = s;
      return s;
    }
  }
  /**
   * <code>optional string form_desc = 7;</code>
   * @return The bytes for formDesc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFormDescBytes() {
    java.lang.Object ref = formDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      formDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_ID_FIELD_NUMBER = 8;
  private int ownerId_;
  /**
   * <code>optional int32 owner_id = 8;</code>
   * @return Whether the ownerId field is set.
   */
  @java.lang.Override
  public boolean hasOwnerId() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional int32 owner_id = 8;</code>
   * @return The ownerId.
   */
  @java.lang.Override
  public int getOwnerId() {
    return ownerId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, petId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, species_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gender_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, weight_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, birth_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, formDesc_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt32(8, ownerId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, petId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, species_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gender_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, weight_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, birth_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, formDesc_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, ownerId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Pet)) {
      return super.equals(obj);
    }
    Pet other = (Pet) obj;

    if (hasPetId() != other.hasPetId()) return false;
    if (hasPetId()) {
      if (getPetId()
          != other.getPetId()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasSpecies() != other.hasSpecies()) return false;
    if (hasSpecies()) {
      if (!getSpecies()
          .equals(other.getSpecies())) return false;
    }
    if (hasGender() != other.hasGender()) return false;
    if (hasGender()) {
      if (!getGender()
          .equals(other.getGender())) return false;
    }
    if (hasWeight() != other.hasWeight()) return false;
    if (hasWeight()) {
      if (getWeight()
          != other.getWeight()) return false;
    }
    if (hasBirth() != other.hasBirth()) return false;
    if (hasBirth()) {
      if (!getBirth()
          .equals(other.getBirth())) return false;
    }
    if (hasFormDesc() != other.hasFormDesc()) return false;
    if (hasFormDesc()) {
      if (!getFormDesc()
          .equals(other.getFormDesc())) return false;
    }
    if (hasOwnerId() != other.hasOwnerId()) return false;
    if (hasOwnerId()) {
      if (getOwnerId()
          != other.getOwnerId()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPetId()) {
      hash = (37 * hash) + PET_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPetId();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasSpecies()) {
      hash = (37 * hash) + SPECIES_FIELD_NUMBER;
      hash = (53 * hash) + getSpecies().hashCode();
    }
    if (hasGender()) {
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
    }
    if (hasWeight()) {
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getWeight();
    }
    if (hasBirth()) {
      hash = (37 * hash) + BIRTH_FIELD_NUMBER;
      hash = (53 * hash) + getBirth().hashCode();
    }
    if (hasFormDesc()) {
      hash = (37 * hash) + FORM_DESC_FIELD_NUMBER;
      hash = (53 * hash) + getFormDesc().hashCode();
    }
    if (hasOwnerId()) {
      hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerId();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Pet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Pet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Pet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Pet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Pet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Pet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Pet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Pet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Pet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Pet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Pet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Pet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Pet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Pet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Pet)
      PetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CatalogOuterClass.internal_static_Pet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CatalogOuterClass.internal_static_Pet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Pet.class, Pet.Builder.class);
    }

    // Construct using Pet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      petId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      species_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      gender_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      weight_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      birth_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      formDesc_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      ownerId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CatalogOuterClass.internal_static_Pet_descriptor;
    }

    @java.lang.Override
    public Pet getDefaultInstanceForType() {
      return Pet.getDefaultInstance();
    }

    @java.lang.Override
    public Pet build() {
      Pet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Pet buildPartial() {
      Pet result = new Pet(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.petId_ = petId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.species_ = species_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.gender_ = gender_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.weight_ = weight_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.birth_ = birth_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.formDesc_ = formDesc_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.ownerId_ = ownerId_;
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Pet) {
        return mergeFrom((Pet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Pet other) {
      if (other == Pet.getDefaultInstance()) return this;
      if (other.hasPetId()) {
        setPetId(other.getPetId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasSpecies()) {
        bitField0_ |= 0x00000004;
        species_ = other.species_;
        onChanged();
      }
      if (other.hasGender()) {
        bitField0_ |= 0x00000008;
        gender_ = other.gender_;
        onChanged();
      }
      if (other.hasWeight()) {
        setWeight(other.getWeight());
      }
      if (other.hasBirth()) {
        bitField0_ |= 0x00000020;
        birth_ = other.birth_;
        onChanged();
      }
      if (other.hasFormDesc()) {
        bitField0_ |= 0x00000040;
        formDesc_ = other.formDesc_;
        onChanged();
      }
      if (other.hasOwnerId()) {
        setOwnerId(other.getOwnerId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Pet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Pet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int petId_ ;
    /**
     * <code>optional int32 pet_id = 1;</code>
     * @return Whether the petId field is set.
     */
    @java.lang.Override
    public boolean hasPetId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 pet_id = 1;</code>
     * @return The petId.
     */
    @java.lang.Override
    public int getPetId() {
      return petId_;
    }
    /**
     * <code>optional int32 pet_id = 1;</code>
     * @param value The petId to set.
     * @return This builder for chaining.
     */
    public Builder setPetId(int value) {
      bitField0_ |= 0x00000001;
      petId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 pet_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      petId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object species_ = "";
    /**
     * <code>optional string species = 3;</code>
     * @return Whether the species field is set.
     */
    public boolean hasSpecies() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string species = 3;</code>
     * @return The species.
     */
    public java.lang.String getSpecies() {
      java.lang.Object ref = species_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        species_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string species = 3;</code>
     * @return The bytes for species.
     */
    public com.google.protobuf.ByteString
        getSpeciesBytes() {
      java.lang.Object ref = species_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        species_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string species = 3;</code>
     * @param value The species to set.
     * @return This builder for chaining.
     */
    public Builder setSpecies(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      species_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string species = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpecies() {
      bitField0_ = (bitField0_ & ~0x00000004);
      species_ = getDefaultInstance().getSpecies();
      onChanged();
      return this;
    }
    /**
     * <code>optional string species = 3;</code>
     * @param value The bytes for species to set.
     * @return This builder for chaining.
     */
    public Builder setSpeciesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      species_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gender_ = "";
    /**
     * <code>optional string gender = 4;</code>
     * @return Whether the gender field is set.
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string gender = 4;</code>
     * @return The gender.
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string gender = 4;</code>
     * @return The bytes for gender.
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string gender = 4;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string gender = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      bitField0_ = (bitField0_ & ~0x00000008);
      gender_ = getDefaultInstance().getGender();
      onChanged();
      return this;
    }
    /**
     * <code>optional string gender = 4;</code>
     * @param value The bytes for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      gender_ = value;
      onChanged();
      return this;
    }

    private int weight_ ;
    /**
     * <code>optional int32 weight = 5;</code>
     * @return Whether the weight field is set.
     */
    @java.lang.Override
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 weight = 5;</code>
     * @return The weight.
     */
    @java.lang.Override
    public int getWeight() {
      return weight_;
    }
    /**
     * <code>optional int32 weight = 5;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(int value) {
      bitField0_ |= 0x00000010;
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 weight = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      bitField0_ = (bitField0_ & ~0x00000010);
      weight_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object birth_ = "";
    /**
     * <code>optional string birth = 6;</code>
     * @return Whether the birth field is set.
     */
    public boolean hasBirth() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string birth = 6;</code>
     * @return The birth.
     */
    public java.lang.String getBirth() {
      java.lang.Object ref = birth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string birth = 6;</code>
     * @return The bytes for birth.
     */
    public com.google.protobuf.ByteString
        getBirthBytes() {
      java.lang.Object ref = birth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string birth = 6;</code>
     * @param value The birth to set.
     * @return This builder for chaining.
     */
    public Builder setBirth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      birth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string birth = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBirth() {
      bitField0_ = (bitField0_ & ~0x00000020);
      birth_ = getDefaultInstance().getBirth();
      onChanged();
      return this;
    }
    /**
     * <code>optional string birth = 6;</code>
     * @param value The bytes for birth to set.
     * @return This builder for chaining.
     */
    public Builder setBirthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000020;
      birth_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object formDesc_ = "";
    /**
     * <code>optional string form_desc = 7;</code>
     * @return Whether the formDesc field is set.
     */
    public boolean hasFormDesc() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string form_desc = 7;</code>
     * @return The formDesc.
     */
    public java.lang.String getFormDesc() {
      java.lang.Object ref = formDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formDesc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string form_desc = 7;</code>
     * @return The bytes for formDesc.
     */
    public com.google.protobuf.ByteString
        getFormDescBytes() {
      java.lang.Object ref = formDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string form_desc = 7;</code>
     * @param value The formDesc to set.
     * @return This builder for chaining.
     */
    public Builder setFormDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      formDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string form_desc = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormDesc() {
      bitField0_ = (bitField0_ & ~0x00000040);
      formDesc_ = getDefaultInstance().getFormDesc();
      onChanged();
      return this;
    }
    /**
     * <code>optional string form_desc = 7;</code>
     * @param value The bytes for formDesc to set.
     * @return This builder for chaining.
     */
    public Builder setFormDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000040;
      formDesc_ = value;
      onChanged();
      return this;
    }

    private int ownerId_ ;
    /**
     * <code>optional int32 owner_id = 8;</code>
     * @return Whether the ownerId field is set.
     */
    @java.lang.Override
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 owner_id = 8;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public int getOwnerId() {
      return ownerId_;
    }
    /**
     * <code>optional int32 owner_id = 8;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(int value) {
      bitField0_ |= 0x00000080;
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 owner_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      bitField0_ = (bitField0_ & ~0x00000080);
      ownerId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Pet)
  }

  // @@protoc_insertion_point(class_scope:Pet)
  private static final Pet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Pet();
  }

  public static Pet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Pet>
      PARSER = new com.google.protobuf.AbstractParser<Pet>() {
    @java.lang.Override
    public Pet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Pet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Pet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Pet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Pet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

